---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, nfsv3 
summary: Diese bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. 
---
= Bekannte Einschränkungen in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. Schauen Sie sich das auch einmal an link:reference-limitations.html["Einschränkungen bei allen Cloud-Providern"].



== Neue Bereitstellungen werden nicht unterstützt

Neue Implementierungen von Cloud Volumes ONTAP 9.6 werden in Azure nicht mehr unterstützt. Sie müssen Cloud Volumes ONTAP 9.7 implementieren.



== HA-Einschränkungen

Die folgenden Einschränkungen betreffen Cloud Volumes ONTAP HA-Paare in Microsoft Azure:

* NFSv4 wird nicht unterstützt. NFSv3 wird unterstützt.
* HA-Paare werden in einigen Regionen nicht unterstützt.
+
https://cloud.netapp.com/cloud-volumes-global-regions["Siehe die Liste der unterstützten Azure Regionen"^].





== CSP-Partner erhalten keine Pay-as-you-go-Lösung

Als Microsoft Cloud Solution Provider (CSP)-Partner können Sie Cloud Volumes ONTAP Explore, Standard oder Premium nicht bereitstellen, da CSP-Partner keine Pay-as-you-go-Abonnements haben. Kunden müssen eine Lizenz erwerben und Cloud Volumes ONTAP BYOL implementieren.
