---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch. 
---
= Einschränkungen bei allen Cloud-Providern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.

Die folgenden Einschränkungen gelten für Cloud Volumes ONTAP bei allen Cloud-Providern: AWS, Azure und Google Cloud.



== Maximal gleichzeitige Replizierungsvorgänge

Die maximale Anzahl gleichzeitiger SnapMirror oder SnapVault Transfers für Cloud Volumes ONTAP beträgt 100 pro Node, unabhängig vom Instanztyp oder Machine-Typ.



== Software-Updates müssen von Cloud Manager abgeschlossen werden

Upgrades von Cloud Volumes ONTAP müssen von Cloud Manager abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.



== Die Cloud Volumes ONTAP-Bereitstellung darf nicht von der Konsole Ihres Cloud-Providers geändert werden

Änderungen an einer Cloud Volumes ONTAP Konfiguration aus der Konsole Ihres Cloud-Providers resultieren in einer nicht unterstützten Konfiguration. Alle Änderungen an den von Cloud Manager erstellten und gemanagten Cloud Volumes ONTAP Ressourcen können sich auf die Systemstabilität auswirken und das Management des Systems durch Cloud Manager vornehmen.



== Festplatten und Aggregate müssen über Cloud Manager gemanagt werden

Alle Festplatten und Aggregate müssen direkt aus Cloud Manager erstellt und gelöscht werden. Sie sollten diese Aktionen nicht über ein anderes Management-Tool ausführen. Dies kann sich auf die Systemstabilität auswirken, die Fähigkeit zum Hinzufügen von Festplatten in der Zukunft beeinträchtigen und möglicherweise Kosten für redundante Cloud-Provider verursachen.



== Einschränkung der SnapManager-Lizenzierung

SnapManager Lizenzen pro Server werden von Cloud Volumes ONTAP unterstützt. Lizenzen pro Storage-System (SnapManager Suite) werden nicht unterstützt.



== Nicht unterstützte ONTAP-Funktionen

Die folgenden Funktionen werden mit Cloud Volumes ONTAP nicht unterstützt:

* Inline-Deduplizierung auf Aggregatebene
* Deduplizierung auf Aggregatebene im Hintergrund
* Disk Maintenance Center
* Festplattenbereinigung
* Fibre Channel (FC)
* Flash Pools
* Unbegrenzte Volumes
* Interface Groups
* LIF-Failover bei Intranode
* MetroCluster
* Mandantenfähigkeit (es wird nur eine SVM für Daten unterstützt)
* RAID4, RAID-DP, RAID-TEC (RAID0 WIRD UNTERSTÜTZT)
* Service Processor
* SnapLock Compliance und Enterprise Mode (nur Cloud WORM wird unterstützt)
* SnapMirror Synchronous
* VLANs

