---
sidebar: sidebar 
permalink: reference-limits-azure.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks 
summary: Cloud Volumes ONTAP verfügt über Einschränkungen bei der Storage-Konfiguration in Azure, um einen zuverlässigen Betrieb zu gewährleisten. Konfigurieren Sie das System nicht mit den Maximalwerten, um eine optimale Performance zu erzielen. 
---
= Storage-Grenzen in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP verfügt über Einschränkungen bei der Storage-Konfiguration, um einen zuverlässigen Betrieb zu gewährleisten. Konfigurieren Sie das System nicht mit den Maximalwerten, um eine optimale Performance zu erzielen.



== Maximale Systemkapazität nach Lizenz

Die maximale Systemkapazität eines Cloud Volumes ONTAP-Systems wird durch seine Lizenz bestimmt. Die maximale Systemkapazität umfasst festplattenbasierten Storage sowie Objekt-Storage für Daten-Tiering. NetApp unterstützt das Übertreffen dieses Limits nicht.

[cols="25,75"]
|===
| Lizenz | Maximale Systemkapazität (Festplatten + Objekt-Storage) 


| Entdecken | 2 tib (Daten-Tiering wird nicht mit Explore unterstützt) 


| Standard | 10 tib 


| Premium | 368 tib 


| BYOL | 368 tib pro Lizenz 
|===
Das Kapazitätslimit liegt für das gesamte HA-Paar. Er erfolgt nicht pro Node. Wenn Sie beispielsweise die Premium-Lizenz verwenden, können Sie bis zu 368 tib Kapazität zwischen beiden Nodes haben.



== Festplatten- und Tiering-Größen werden nach VM-Größe begrenzt

Die unten aufgeführten Festplattengrenzwerte gelten für Festplatten, die Benutzerdaten enthalten. Die Grenzen beinhalten nicht die Boot-Festplatte und Root-Festplatte. Die folgenden Tabellen zeigen die maximale Systemkapazität nach VM-Größe mit Festplatten oder allein, mit Festplatten und selten benötigten Daten-Tiering in den Objekt-Storage.

Festplattenbeschränkungen werden durch die VM-Größe nur für Premium- und BYOL-Lizenzen angezeigt, da aufgrund von Kapazitätsbeschränkungen bei Explore und Standard-Lizenzen keine Limits für Festplatten erreicht werden können.

* Systeme mit einem Node können Standard-HDD-verwaltete Standardfestplatten, über Standard-SSD-verwaltete Festplatten und Premium-SSD-gemanagte Festplatten mit bis zu 32 tib pro Festplatte verwenden. Die Anzahl der unterstützten Festplatten variiert je nach VM-Größe.
* HA-Systeme verwenden Premium-Blobs als Festplatten, mit bis zu 8 tib pro Seite BLOB. Die Anzahl der unterstützten Festplatten variiert je nach VM-Größe.




=== Single Node mit Premium-Lizenz

[cols="14,20,31,33"]
|===
| Die VM-Größe | Max. Festplatten pro Node | Maximale Systemkapazität mit Festplatten allein | Maximale Systemkapazität mit Festplatten und Daten-Tiering 


| DS5_v2 | 63 | 368 tib | 368 tib 


| DS14_v2 | 63 | 368 tib | 368 tib 


| DS15_v2 | 63 | 368 tib | 368 tib 
|===


=== Einzelner Node mit einer oder mehreren BYOL-Lizenzen


NOTE: Bei einigen VM-Typen benötigen Sie mehrere BYOL-Lizenzen, um die unten aufgeführte maximale Systemkapazität zu erreichen. Beispielsweise würden Sie 6 BYOL-Lizenzen benötigen, um mit DS5_v2 2 PiB zu erreichen.

[cols="10,18,18,18,18,18"]
|===
| Die VM-Größe | Max. Festplatten pro Node 2+| Maximale Systemkapazität mit einer Lizenz 2+| Maximale Systemkapazität mit mehreren Lizenzen 


2+|  | *Festplatten allein* | *Festplatten + Daten-Tiering* | *Festplatten allein* | *Festplatten + Daten-Tiering* 


| DS3_v2 | 15 | 368 tib | 368 tib | 480 tib | 368 tib x jede Lizenz 


| DS4_v2 | 31 | 368 tib | 368 tib | 896 tib | 368 tib x jede Lizenz 


| DS5_v2 | 63 | 368 tib | 368 tib | 896 tib | 368 tib x jede Lizenz 


| DS13_v2 | 31 | 368 tib | 368 tib | 896 tib | 368 tib x jede Lizenz 


| DS14_v2 | 63 | 368 tib | 368 tib | 896 tib | 368 tib x jede Lizenz 


| DS15_v2 | 63 | 368 tib | 368 tib | 896 tib | 368 tib x jede Lizenz 
|===


=== HA-Paare mit einer Premium-Lizenz

[cols="14,20,31,33"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar | Maximale Systemkapazität mit Festplatten allein | Maximale Systemkapazität mit Festplatten und Daten-Tiering 


| DS5_v2 | 63 | 368 tib | 368 tib 


| DS14_v2 | 63 | 368 tib | 368 tib 


| DS15_v2 | 63 | 368 tib | 368 tib 
|===


=== HA-Paare mit einer oder mehreren BYOL-Lizenzen

[cols="10,18,18,18,18,18"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar 2+| Maximale Systemkapazität mit einer Lizenz 2+| Maximale Systemkapazität mit mehreren Lizenzen 


2+|  | *Festplatten allein* | *Festplatten + Daten-Tiering* | *Festplatten allein* | *Festplatten + Daten-Tiering* 


| DS4_v2 | 31 | 368 tib | 368 tib | 248 tib | 368 tib x jede Lizenz 


| DS5_v2 | 63 | 368 tib | 368 tib | 504 tib | 368 tib x jede Lizenz 


| DS13_v2 | 31 | 368 tib | 368 tib | 248 tib | 368 tib x jede Lizenz 


| DS14_v2 | 63 | 368 tib | 368 tib | 504 tib | 368 tib x jede Lizenz 


| DS15_v2 | 63 | 368 tib | 368 tib | 504 tib | 368 tib x jede Lizenz 
|===


== Aggregatgrenzen

Cloud Volumes ONTAP nutzt Azure Storage als Festplatten und gruppiert diese in _Aggregate_. Aggregate stellen Storage auf Volumes zur Verfügung.

[cols="2*"]
|===
| Parameter | Grenze 


| Maximale Anzahl an Aggregaten | Entspricht der Festplattengrenze 


| Maximale Aggregatgröße | 352 tib Rohkapazität für einzelnen Node ^1,^ ^2^ 96 tib Rohkapazität für HA-Paare ^1^ 


| Disks pro Aggregat | 1-12 ^3^ 


| Maximale Anzahl von RAID-Gruppen pro Aggregat | 1 
|===
Hinweise:

. Die Kapazitätsgrenze für das Aggregat basiert auf den Festplatten, die das Aggregat umfassen. Die Obergrenze enthält keinen Objekt-Storage, der für Daten-Tiering verwendet wird.
. Die 352 tib Beschränkung wird ab 9.6 P3 unterstützt. Versionen vor 9.6 P3 unterstützen bis zu 200 tib Rohkapazität in einem Aggregat auf einem System mit einem einzelnen Node.
. Alle Festplatten in einem Aggregat müssen dieselbe Größe haben.




== Logische Storage-Einschränkungen

[cols="22,22,56"]
|===
| Logischer Storage | Parameter | Grenze 


| *Storage Virtual Machines (SVMs)* | Maximale Anzahl für Cloud Volumes ONTAP (HA-Paar oder Single Node) | Eine Datenservice-SVM und eine Ziel-SVM für die Disaster Recovery verwendet. Sie können die Ziel-SVM für den Datenzugriff aktivieren, wenn ein Ausfall auf der Quell-SVM auftritt. ^1^ die einheitliche SVM für Daten umfasst das gesamte Cloud Volumes ONTAP System (HA-Paar oder ein Node). 


.2+| *Dateien* | Maximale Größe | 16 tib 


| Maximale Anzahl pro Volume | Volumengröße abhängig, bis zu 2 Milliarden 


| *FlexClone Volumes* | Hierarchische Klontiefe ^2^ | 499 


.3+| *FlexVol Volumes* | Maximal pro Node | 500 


| Mindestgröße | 20 MB 


| Maximale Größe | 100 tib 


| *Qtrees* | Maximale Anzahl pro FlexVol Volume | 4,995 


| *Snapshot Kopien* | Maximale Anzahl pro FlexVol Volume | 1,023 
|===
Hinweise:

. Cloud Manager bietet keine Einrichtungs- oder Orchestrierungsunterstützung für SVM Disaster Recovery. Zudem werden für zusätzliche SVMs keine Storage-Aufgaben unterstützt. Sie müssen System Manager oder die CLI für die SVM-Disaster Recovery verwenden.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Express Guide zur Vorbereitung des SVM-Disaster Recovery"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["SVM Disaster Recovery Express Guide"^]


. Diese hierarchische Klontiefe ist die maximale Tiefe einer geschachtelten Hierarchie der FlexClone Volumes, die aus einem einzelnen FlexVol Volume erstellt werden kann.




== ISCSI-Storage-Einschränkungen

[cols="3*"]
|===
| ISCSI-Storage | Parameter | Grenze 


.4+| *LUNs* | Maximal pro Node | 1,024 


| Die maximale Anzahl der LUN-Zuordnungen | 1,024 


| Maximale Größe | 16 tib 


| Maximale Anzahl pro Volume | 512 


| *Igroups* | Maximal pro Node | 256 


.2+| *Initiatoren* | Maximal pro Node | 512 


| Die maximale Anzahl pro Initiatorgruppe | 128 


| *ISCSI-Sitzungen* | Maximal pro Node | 1,024 


.2+| *LIFs* | Maximal pro Port | 32 


| Maximal pro Portsatz | 32 


| *Portsätze* | Maximal pro Node | 256 
|===