---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, nfsv3 
summary: Diese bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. 
---
= Bekannte Einschränkungen in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. Schauen Sie sich das auch einmal an link:reference-limitations.html["Einschränkungen bei allen Cloud-Providern"].



== Beschränkungen bei der Verwendung von Azure VM-Erweiterungen

Cloud Volumes ONTAP unterstützt in einer Implementierung keine Erweiterungen für Azure Virtual Machine (VM) und VM-Applikationen. Die Verwendung von Cloud Volumes ONTAP in Azure mit VM-Erweiterungen führt zu Verzögerungen bei Operationen, und NetApp empfiehlt, diese zu vermeiden.



== Neue Implementierungen werden nicht unterstützt

Neue Implementierungen von Cloud Volumes ONTAP 9.6 werden in Azure nicht mehr unterstützt. Sie müssen Cloud Volumes ONTAP 9.7 implementieren.



== HA-Einschränkungen

Die folgenden Einschränkungen betreffen Cloud Volumes ONTAP HA-Paare in Microsoft Azure:

* NFSv4 wird nicht unterstützt. NFSv3 wird unterstützt.
* HA-Paare werden in einigen Regionen nicht unterstützt.
+
https://bluexp.netapp.com/cloud-volumes-global-regions["Siehe die Liste der unterstützten Azure Regionen"^]


